inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Rails:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

Bundler/DuplicatedGem:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Lint/AssignmentInCondition:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/ClassLength:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Alias:
  Enabled: false
