inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

Bundler/DuplicatedGem:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/RescueException:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SignalException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/Next:
  Enabled: false

Metrics:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Alias:
  Enabled: false
