sequenceDiagram
    SmartProxyAPI->>SmartProxyAPI: /tasks/launch
    SmartProxyAPI->>SmartProxyAPI: TaskLauncherRegistry.fetch(params['operation'])
    SmartProxyAPI->>+BatchTaskLauncher: launch!(input = params['input'])
    participant SingleLauncher
    BatchTaskLauncher->>dynflow: trigger(action=BatchAction, input)
    dynflow->>+BatchAction: plan(launcher, input)
    BatchAction->>BatchTaskLauncher: launch_children(parent_action = self, input)
    loop Every child in the input [{child_id => child_input}]
    BatchTaskLauncher->>BatchTaskLauncher: SingleLauncher = child_launcher(parent_action)
    BatchTaskLauncher->>+SingleLauncher: launch!(child_input = input[foreman_child_plan_id])
    SingleLauncher->>dynflow: results = trigger(parent, child_input)
    SingleLauncher->>-BatchTaskLauncher: results[foreman_child_plan_id] = results
    end
    BatchTaskLauncher->>-SmartProxyAPI: results
